[project]
name = "python-cursus"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "html2markdown>=0.1.7",
    "html2text>=2024.2.26",
    "markdown[toc]==3.7",
    "requests>=2.32.3",
]
